# Generated by Django 4.1.1 on 2022-10-01 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('document', models.CharField(blank=True, max_length=150)),
            ],
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('name', models.CharField(max_length=150, verbose_name='Company')),
                ('position', models.CharField(help_text='Sobre a posição da vaga', max_length=100)),
                ('contact', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('submition_date', models.DateField(blank=True, default=datetime.date(2022, 10, 1))),
                ('interview_date', models.DateField(blank=True, default=datetime.date(2022, 10, 1), help_text='Data da entrevista')),
                ('aplication_status', models.CharField(choices=[('AGUARDANDO_CONTATO', 'AGUARDANDO CONTATO'), ('REJEITADO', 'REJEITADO'), ('EM_ANALISE', 'EM ANALISE'), ('PROXIMA_ENTREVISTA', 'PROXIMA ENTREVISTA'), ('ACEITO', 'ACEITO')], default='AGUARDANDO_CONTATO', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('document_send', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_send', to='core.documents')),
            ],
            options={
                'verbose_name': 'Company',
            },
            bases=('core.base',),
        ),
    ]
