# Generated by Django 4.1.1 on 2022-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='companies',
            name='interview_date',
            field=models.DateField(blank=True, help_text='Data da entrevista'),
        ),
    ]
