# Generated by Django 4.1.1 on 2022-10-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='aplication_status',
            field=models.CharField(choices=[('AGUARDANDO CONTATO', 'AGUARDANDO CONTATO'), ('REJEITADO', 'REJEITADO'), ('EM ANALISE', 'EM ANALISE'), ('PROXIMA ENTREVISTA', 'PROXIMA ENTREVISTA'), ('ACEITO', 'ACEITO')], default='AGUARDANDO_CONTATO', max_length=20),
        ),
    ]
