# Generated by Django 4.1.1 on 2022-10-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companies_options_alter_documents_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='obs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='document_send',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_send', to='core.documents'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='interview_date',
            field=models.DateField(blank=True, help_text='Data da entrevista', null=True),
        ),
    ]
