# Generated by Django 4.1.1 on 2022-10-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companies_obs_alter_companies_document_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='companies',
            name='document_send',
        ),
        migrations.AddField(
            model_name='companies',
            name='document_send',
            field=models.ManyToManyField(blank=True, null=True, related_name='documents_send', to='core.documents'),
        ),
    ]
