# Generated by Django 4.1.1 on 2022-11-24 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_companies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='aplication_status',
            field=models.CharField(choices=[('AGUARDANDO CONTATO', 'AGUARDANDO CONTATO'), ('REJEITADO', 'REJEITADO'), ('EM ANALISE', 'EM ANALISE'), ('PROXIMA ENTREVISTA', 'PROXIMA ENTREVISTA'), ('ACEITO', 'ACEITO')], default='AGUARDANDO_CONTATO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recrutador'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='document_send',
            field=models.ManyToManyField(blank=True, null=True, related_name='documents_send', to='core.documents', verbose_name='Documento(s) enviado'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da entrevista'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='position',
            field=models.CharField(help_text='Sobre a posição da vaga', max_length=100, verbose_name='Vaga'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='submition_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 24), verbose_name='Data de inscrição'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.CharField(blank=True, max_length=150, verbose_name='Documento(s)'),
        ),
    ]
