# Generated by Django 4.1.1 on 2022-10-02 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companies_link_remove_companies_document_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='submition_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 2)),
        ),
    ]
