# Generated by Django 4.1.1 on 2022-12-15 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_companies_submition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='submition_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 15), verbose_name='Data de inscrição'),
        ),
    ]
