# Generated by Django 4.1.1 on 2022-10-04 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_companies_submition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='interview_date',
            field=models.DateTimeField(blank=True, help_text='Data da entrevista', null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='submition_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 4)),
        ),
    ]
