# Generated by Django 4.1.1 on 2022-12-15 02:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_companies_submition_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedCompanies',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('name', models.CharField(max_length=150, verbose_name='Empresa')),
                ('position', models.CharField(help_text='Sobre a posição da vaga', max_length=100, verbose_name='Vaga')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recrutador')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('submition_date', models.DateField(blank=True, default=datetime.date(2022, 12, 15), verbose_name='Data de inscrição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('obs', models.TextField(blank=True, max_length=1000, null=True)),
                ('document_send', models.ManyToManyField(blank=True, null=True, related_name='documents_send', to='core.documents', verbose_name='Documento(s) enviado')),
            ],
            options={
                'verbose_name': 'Applied Company',
                'verbose_name_plural': 'Applied Companies',
                'ordering': ['-updated_at'],
            },
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('describe', models.CharField(max_length=100, verbose_name='Process')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
            bases=('core.base',),
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.AddField(
            model_name='appliedcompanies',
            name='interviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.interviews'),
        ),
        migrations.AddField(
            model_name='appliedcompanies',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processes'),
        ),
        migrations.AddField(
            model_name='appliedcompanies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
