# Generated by Django 4.1.1 on 2022-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_companies_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name'),
        ),
    ]
