# Generated by Django 4.1.1 on 2022-10-07 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_companies_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='submition_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 7)),
        ),
    ]
