# Generated by Django 4.1.1 on 2022-12-16 02:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_interviews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcompanies',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.processes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processes',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliedcompanies',
            name='submition_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 16), verbose_name='Data de inscrição'),
        ),
    ]
