# Generated by Django 3.2.16 on 2022-12-17 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_processes_applied_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcompanies',
            name='submition_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 17), verbose_name='Data de inscrição'),
        ),
    ]
