# Generated by Django 3.2.16 on 2022-12-31 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_appliedcompanies_submition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliedcompanies',
            name='submition_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 31), verbose_name='Data de inscrição'),
        ),
    ]
