# Generated by Django 3.2.16 on 2022-12-31 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20221231_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processes',
            old_name='owner',
            new_name='user',
        ),
    ]
